### ISSUE TITLE
If multi class in one image can be trained by FLORA?

### ISSUE THREAD

**Issue by misi0202** [shadowpa0327/FLORA#3]
I noticed the data structure should be divided in class1 folder or class2, but if an image  has different classes. How to train it?
Expect for you reply :)

**Comment by shadowpa0327** [comment]
Sorry for the late reply. 
We do not have any restriction on the folder structure of the dataset. The structure mentioned in the README is the format related to ImageNet dataset. If your dataset have your own layout, you can implement your own [dataset modules](https://pytorch.org/tutorials/beginner/basics/data_tutorial.html#creating-a-custom-dataset-for-your-files) and register it over [here](https://github.com/shadowpa0327/FLORA/blob/master/data/build.py#L113), then it might work.
